### ISSUE TITLE
ENOLIFECYCLE when installing cartridge-images using CLI

### ISSUE THREAD

**Issue by jajeffries** [cartridge/cartridge-images#2]
# Project version:
0.0.4

## Issue type:
> Tick one of the below and label if necessary

- [x] Bug

### Expected behaviour:
Cartridge-images is successfully installed

### Actual behaviour:
	Error: Command failed: C:\windows\system32\cmd.exe /s /c "npm i -D cartridge-images"
	gyp ERR! build error
	gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code:
	 1
	gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\n
	ode-gyp\lib\build.js:276:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	gyp ERR! System Windows_NT 6.3.9600
	gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin
	\\node-gyp.js" "rebuild"
	gyp ERR! cwd C:\workspace\personal\node_modules\sharp
	gyp ERR! node -v v0.12.2
	gyp ERR! node-gyp -v v3.3.1
	gyp ERR! not ok
	npm WARN test@0.0.1 No description
	npm WARN test@0.0.1 No repository field.
	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\np
	m\\bin\\npm-cli.js" "i" "-D" "cartridge-images"
	npm ERR! node v0.12.2
	npm ERR! npm  v3.8.7
	npm ERR! code ELIFECYCLE
	npm ERR! sharp@0.14.1 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the sharp@0.14.1 install script 'node-gyp rebuild'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the sharp package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs sharp
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls sharp
	npm ERR! There is likely additional logging output above.
	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\workspace\personal\npm-debug.log

### Steps to reproduce the behaviour:
1. run `cartridge new`
2. select Static website
3. enter a name, author and description
4. select the cartridge-images expansion pack
5. Confirm that you want to install

I'm running on windows with node 0.12.2 and npm 3.8.7.

**Comment by tawashley** [comment]
@jajeffries Sorry for the long absence in replying to this issue.

The log above shows an issue in `sharp`, the main module in `gulp-responsive` to generate images of varying sizes. On Windows, this requires extra setup to get working and assumes areas such as Visual Studio being installed etc.

Due to this, the responsive aspect of `cartridge-images` has been removed and a new major version has been released. You should now be able to install the module without any issues. If you could possibly confirm if this has fixed you issue it would be greatly appreciated.

Thanks
Tris

**Comment by jajeffries** [comment]
@tawashley I can now install correctly. Thanks.
